"""Detection-rule generation from the C2DETECT signature database.

Turns the bundled C2 fingerprints into **deployable defensive rules** so you can
push C2DETECT's intelligence straight into your stack:

* **Sigma** — vendor-neutral SIEM rules (TLS / proxy log sources), one per C2
  family, keyed on high-confidence TLS fingerprints (JA3/JA3S/JA4/JARM) and,
  where useful, default user-agents and URIs.
* **Suricata** — IDS/IPS rules (``tls`` JA3/JA4 hash matches, ``http`` URI and
  user-agent content matches) with deterministic SIDs in a dedicated range.

Everything is generated from public, documented out-of-the-box defaults already
shipped in :data:`c2detect.core._DB`. Standard library only; output is plain
text (hand-built YAML / Suricata syntax) so there are no dependencies.

This is purely defensive: the rules *detect* known C2 infrastructure. Nothing
here describes how to operate or build a C2.
"""

from __future__ import annotations

import hashlib
from typing import Iterable

from .core import Signature, signatures as _default_signatures

# SIDs live in a private, high range to avoid clashing with ET/Talos rule sets.
_SID_BASE = 9_200_000
_RULE_DATE = "2026/06/21"
_ATTACK_TAGS = ("attack.command_and_control", "attack.t1071.001")


def _slug(family: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in family).strip("_")


def _stable_uuid(seed: str) -> str:
    h = hashlib.md5(seed.encode("utf-8")).hexdigest()
    return f"{h[:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:32]}"


# --------------------------------------------------------------------------- #
# Sigma
# --------------------------------------------------------------------------- #
def sigma_rule(sig: Signature) -> str:
    """Render one Sigma rule (YAML) for a single C2 family."""
    selections: list[tuple[str, list[str]]] = []
    if sig.ja3:
        selections.append(("ja3", [f"        ja3_hash:"] + [f"            - '{v}'" for v in sig.ja3]))
    if sig.ja3s:
        selections.append(("ja3s", [f"        ja3s_hash:"] + [f"            - '{v}'" for v in sig.ja3s]))
    if sig.ja4:
        selections.append(("ja4", [f"        ja4:"] + [f"            - '{v}'" for v in sig.ja4]))
    if sig.jarm:
        selections.append(("jarm", [f"        jarm:"] + [f"            - '{v}'" for v in sig.jarm]))

    if not selections:
        # fall back to user-agent / uri if a family has no TLS fingerprint
        if sig.user_agents:
            selections.append(("ua", [f"        c-useragent|contains:"] + [f"            - '{v}'" for v in sig.user_agents]))
        if sig.uris:
            distinctive = [u for u in sig.uris if len(u) >= 5]
            if distinctive:
                selections.append(("uri", [f"        cs-uri-stem|contains:"] + [f"            - '{u}'" for u in distinctive]))

    if not selections:
        return ""  # nothing strong enough to key a rule on

    names = [n for n, _ in selections]
    condition = " or ".join(names)
    lines: list[str] = []
    lines.append(f"title: C2DETECT — {sig.family} default network fingerprint")
    lines.append(f"id: {_stable_uuid('c2detect:' + sig.family)}")
    lines.append("status: experimental")
    desc = sig.description or f"{sig.family} default C2 network indicators."
    lines.append(f"description: {desc}")
    if sig.references:
        lines.append("references:")
        for r in sig.references:
            lines.append(f"    - {r}")
    lines.append("author: Cognis Digital (generated by c2detect)")
    lines.append(f"date: {_RULE_DATE}")
    lines.append("logsource:")
    lines.append("    category: tls" if (sig.ja3 or sig.ja3s or sig.ja4 or sig.jarm) else "    category: proxy")
    lines.append("detection:")
    for name, body in selections:
        lines.append(f"    {name}:")
        lines.extend(body)
    lines.append(f"    condition: {condition}")
    lines.append(f"level: {'critical' if sig.severity == 'critical' else 'high'}")
    lines.append("tags:")
    for t in _ATTACK_TAGS:
        lines.append(f"    - {t}")
    lines.append(f"    - c2detect.family.{_slug(sig.family).lower()}")
    return "\n".join(lines) + "\n"


def to_sigma(sigs: Iterable[Signature] | None = None) -> str:
    """Render the whole DB as a multi-document Sigma file."""
    sigs = tuple(sigs) if sigs is not None else _default_signatures()
    docs = [r for r in (sigma_rule(s) for s in sigs) if r]
    return "\n---\n".join(docs)


# --------------------------------------------------------------------------- #
# Suricata
# --------------------------------------------------------------------------- #
def suricata_rules(sig: Signature, sid_start: int) -> tuple[list[str], int]:
    """Render Suricata rules for one family; return (rules, next_sid)."""
    rules: list[str] = []
    sid = sid_start
    fam = _slug(sig.family)
    # Suricata reference values must be a single whitespace-free token; point at
    # the c2detect repo (the prose source citations live in the Sigma output).
    ref = "github.com/cognis-digital/c2detect"
    cls = "trojan-activity"

    def meta() -> str:
        return (f'metadata:c2_family {fam}, source c2detect, '
                f'confidence high; classtype:{cls}; sid:{sid}; rev:1;')

    for h in sig.ja3:
        rules.append(
            f'alert tls any any -> any any (msg:"C2DETECT {sig.family} default JA3"; '
            f'ja3.hash; content:"{h}"; reference:url,{ref}; {meta()})')
        sid += 1
    for h in sig.ja4:
        rules.append(
            f'alert tls any any -> any any (msg:"C2DETECT {sig.family} default JA4"; '
            f'ja4.hash; content:"{h}"; reference:url,{ref}; {meta()})')
        sid += 1
    for ua in sig.user_agents:
        esc = ua.replace('"', '\\"')
        rules.append(
            f'alert http any any -> any any (msg:"C2DETECT {sig.family} default User-Agent"; '
            f'flow:established,to_server; http.user_agent; content:"{esc}"; '
            f'reference:url,{ref}; {meta()})')
        sid += 1
    for uri in (u for u in sig.uris if len(u) >= 5):
        rules.append(
            f'alert http any any -> any any (msg:"C2DETECT {sig.family} staging URI {uri}"; '
            f'flow:established,to_server; http.uri; content:"{uri}"; '
            f'reference:url,{ref}; {meta()})')
        sid += 1
    return rules, sid


def to_suricata(sigs: Iterable[Signature] | None = None) -> str:
    """Render the whole DB as a Suricata rules file."""
    sigs = tuple(sigs) if sigs is not None else _default_signatures()
    header = [
        "# C2DETECT — generated Suricata rules",
        "# Defensive detection of documented default C2 fingerprints.",
        "# SIDs in the 9.2M range; tune/threshold before production use.",
        "",
    ]
    out: list[str] = []
    sid = _SID_BASE
    for s in sigs:
        family_rules, sid = suricata_rules(s, sid)
        if family_rules:
            out.append(f"# --- {s.family} ---")
            out.extend(family_rules)
            out.append("")
    return "\n".join(header + out)


def generate(fmt: str, sigs: Iterable[Signature] | None = None) -> str:
    fmt = fmt.lower()
    if fmt == "sigma":
        return to_sigma(sigs)
    if fmt == "suricata":
        return to_suricata(sigs)
    raise ValueError(f"unknown rule format: {fmt!r} (use 'sigma' or 'suricata')")
